# Generated by Django 3.2.8 on 2022-05-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='correctoption',
            field=models.TextField(max_length=2),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option1',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option2',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option3',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option4',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(max_length=200),
        ),
    ]
